sudo: required
services:
  - docker

language: python
python: ["3.6"]

install:
  - pip install pipenv
  - pipenv install --dev
  - make build_image

script:
  - make test_image

after_success:
  - if ["$TRAVIS_BRANCH" == "master"]; then
      docker login -u "$REGISTRY_USERNAME" -p "$REGISTRY_PASSWORD";
      make push_image
    fi
